export type {
  Project,
  Workspace,
  SessionInfo as ClientSession,
  MessagePage as ClientMessagePage,
  SessionStatus as ClientSessionStatus,
  SessionModel as ClientSessionModel,
  ThinkingLevel as ClientThinkingLevel,
  SlashCommand as ClientCommand,
  FileSuggestion as ClientFileSuggestion,
  CommandOption as ClientCommandOption,
  CommandResult as ClientCommandResult,
  SessionActivity as ClientSessionActivity,
  SessionUiEvent,
  GlobalSessionEvent,
} from "../shared/apiTypes.js";
